import esbuild from "esbuild";
import process from "process";
import builtins from "builtin-modules";

// 构建产物顶部的来源说明注释
const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/
`;

// 是否为生产构建（npm run build 时传入 production 参数）
const prod = process.argv[2] === "production";

const context = await esbuild.context({
	banner: {
		js: banner,
	},
	entryPoints: ["src/main.ts"],
	bundle: true,
	// obsidian / electron / codemirror 由 Obsidian 运行时提供，不打进产物
	external: [
		"obsidian",
		"electron",
		"@codemirror/autocomplete",
		"@codemirror/collab",
		"@codemirror/commands",
		"@codemirror/language",
		"@codemirror/lint",
		"@codemirror/search",
		"@codemirror/state",
		"@codemirror/view",
		"@lezer/common",
		"@lezer/highlight",
		"@lezer/lr",
		...builtins,
	],
	format: "cjs",
	target: "es2018",
	logLevel: "info",
	sourcemap: prod ? false : "inline",
	// 生产构建压缩（139-B）：仅去空白/短变量（标准压缩非混淆，社区插件允许），
	// dev 保持可读便于断点调试
	minify: prod,
	treeShaking: true,
	outfile: "main.js",
});

if (prod) {
	// 生产构建：一次性构建后退出
	await context.rebuild();
	process.exit(0);
} else {
	// 开发模式：监听文件变化，自动增量重新构建
	await context.watch();
}
